export const Status = ["",
    "Account time out.",
    "User not found!",
    "Logged out successfully!",
    "Successfully logged in!",
    "Please fill up all fields!",
    "Username or password is not correct, check and try again.",
    "Verification code sent!",
    "Failed to send email",
    "Username must be at least 6 and at most 16 characters.",
    "Email is incorrect.",
    "Email has been successfully verified!",
    "Password must be at least 8 and at most 16 characters.",
    "An account is already created with that username.",
    "An account is already created with that mail.",
    "Account is verified successfully!",
    "Wrong code, check and try again!",
    "Code must be 6 digits only.",
    "Saved successfully!",
    "Current password is wrong",
    "Changed successfully",
    "Your information is successfully updated!",
    "This is your current username!",
    "Passwords do not match!",
    "Password successfully changed!",
    "Password update failed",
    "Username changed successfully!",
    "Product must contain at least 1 picture!",
    "Product is successfully deleted!",
    "Products has been deleted successfully!",
    "Product has been successfully updated!",
    "Product is successfully added in cart!",
    "Product is removed from cart!",
    "Your cart is currently empty. Start exploring our amazing products and add your favorites!",
    "There is no account registered with this Email address!",
    "There is no account registered with this Username!"
]