export const categories = [
    "Trees",
    "Shrubs",
    "Herbs",
    "Climbers",
    "Creepers",
    "Ferns",
    "Mosses",
    "Algae",
    "Grasses",
    "Succulents",
    "Cacti",
    "Bamboo",
    "Palms",
    "Aquatic Plants",
    "Orchids",
    "Carnivorous Plants",
    "Medicinal Plants",
    "Flowering Plants",
    "Non-Flowering Plants",
    "Fruits",
    "Vegetables",
    "Spices",
    "Edible Plants",
    "Indoor Plants",
    "Outdoor Plants",
    "Perennials",
    "Annuals",
    "Biennials",
    "Evergreens",
    "Deciduous Plants",
    "Native Plants",
    "Exotic Plants",
    "Agricultural Crops",
    "Forestry Plants"
]